version: '3.8'

services:
  bridge-trl:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: bridge_trl_service
    network_mode: host
    restart: unless-stopped
